server:
  port: 8064

halconfig:
  filesystem:
    path: ~/.hal/config

spinnaker:
  artifacts:
    debian: https://dl.bintray.com/spinnaker-releases/debians
    docker: gcr.io/spinnaker-marketplace
    kubernetes: gcr.io/kubernetes-spinnaker
  config:
    input:
      writerEnabled: false
      bucket: halconfig
      s3Enabled: false

endpoints:
  env:
    sensitive: false
  autoconfig:
    sensitive: false
  resolvedEnv:
    sensitive: false
  beans:
    sensitive: false
  shutdown:
    enabled: true
    sensitive: false

backup:
  google:
    enabled: false

retrofit:
  logLevel: BASIC

security:
  basic:
    enabled: false
